# Site Settings
title: Lind Chen | - Bella Ciao
email: cozlind@live.com
description: The homepage of Lind Chen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cozlind.com" # the base hostname & protocol for your site
enforce_ssl: www.cozlind.com
url: "https://cozlind.com" # the base hostname & protocol for your site
enforce_ssl: cozlind.com
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: cozlind
user_description: Bella Ciao
disqus_username: cozlind

# Social Media
# Remove the item if you don't need it
github_username: cozlind
facebook_username: your.cozlind
twitter_username: cozlind
instagram_username: instagram_username
linkedin_username: cozlind
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Project
    url: /
#  - title: Art
#    url: /Art/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
