# Site Settings
title: Lind Chen | - Bella Ciao
email: cozlind@live.com
description: The homepage of Lind Chen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cozlind.com"
enforce_ssl: cozlind.com
# url: "https://www.cozlind.com"
# enforce_ssl: www.cozlind.com
google_analytics: "UA-112423409-1" 

# User Settings
username: cozlind
user_description: Game Developer
disqus_username: cozlind

# Social Media
# Remove the item if you don't need it
username: cozlind
facebook_username: your.cozlind

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Project
    url: /
#  - title: Art
#    url: /Art/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
